server:
  port: 8901

spring:
  application:
    name: nacos_gateway_demo
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: cde61379-0d83-4064-8508-405b7eb0f04c
    gateway:
      routes:
        - id: host-route
          # 注意：这里的这个uri只能填写成ip:port的写法，或者直接写注册中心的服务地址【lb://service-provider 匹配后提供服务的路由地址，这里的service-provider是服务名】
          # 当路由适配后，会将这个uri地址替换请求中的ip和端口，其他的请求地址不变（如http://localhost:8901/json/parse/array/v2），则自动转发到（http://localhost:30010/json/parse/array/v2）
          uri: lb://nacos-demo #http://localhost:30010
          predicates:
#            - Path=/json/parse/array  # 匹配url路径
#            - After=2017-01-20T17:42:47.789+08:00  # 时间点之后的所有请求
#            - Before=2022-01-20T17:42:47.789+08:00  # 时间点之前的所有请求
            - Between=2017-01-20T17:42:47.789+08:00, 2022-01-20T17:42:47.789+08:00  # 时间段之间的所有请求